[package]
name = "domain-service"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
tokio = { version = "1.42.0", features = ["full"]}
# domain-model以外の層に依存してはいけない
domain-model = { path = "../domain-model" }

[dev-dependencies]
mockall = "0.13.1"
