[package]
name = "app-service"
version = "0.1.0"
edition = "2021"

[dependencies]
domain-service = { path = "../domain-service" }
domain-model = { path = "../domain-model" }

[dev-dependencies]
mockall = "0.13.1"